// originally from https://p5js.org/reference/#/p5/atan2

const texts = [
  `WOODS OF ARCADY ARE DEAD AND OVER IS THEIR`,
  `DERMOT TREADS UPON THE LAWN AND TO THE ARMCHAIR GOES AND NOW THE OLD MAN’S DREAMS ARE GONE HE`,
  `DANCE WE MOCKED AT TIME AND FATE AND CHANCE AND SWEPT OUT OF THE WATTLED HALL AND CAME TO WHERE THE DEWDROPS FALL AMONG THE FOAMDROPS OF THE SEA AND THERE WE HUSHED THE REVELRY; AND GATHERING ON OUR BROWS A FROWN BENT ALL OUR SWAYING BODIES DOWN AND TO THE WAVES THAT GLIMMER BY THAT SLOPING GREEN DE DANAAN SOD SANG GOD IS JOY`,
  `TRUTH LEST ALL THY TOILING ONLY BREEDS NEW DREAMS NEW DREAMS; THERE IS NO TRUTH`,
  `WATERS AND THE WILD WITH A FAERY HAND IN HAND FOR THE WORLD’S MORE FULL OF WEEPING`,
  `SHAKES OUT HER LONG DARK HAIR THAT HIDES AWAY THE DYING SUN AND SHEDS FAINT ODOURS THROUGH THE AIR: WHEN MY HAND PASSED FROM WIRE TO WIRE IT QUENCHED WITH SOUND LIKE FALLING DEW THE WHIRLING AND THE WANDERING FIRE; BUT LIFT A MOURNFUL ULALU FOR THE KIND WIRES ARE TORN AND STILL AND I MUST WANDER WOOD AND HILL THROUGH SUMMER’S HEAT AND WINTER’S`,
  `SPIRITS OF EVIL SNATCH THEIR PREY ALMOST OUT OF THE VERY HAND OF GOD; AND DAY BY DAY THEIR POWER IS MORE AND MORE`,
  `I WILL CONFRONT THIS MIGHTY SPIRIT ALONE; BE NOT AFRAID THE FATHER IS WITH US`,
  `GOD IS JOY`,
  `WORSHIP DUSTY DEEDS NOR SEEK; FOR THIS IS ALSO SOOTH; TO`,
  `CAOLTE AND CONAN AND FINN WERE THERE WHEN WE FOLLOWED A DEER WITH OUR BAYING HOUNDS WITH BRAN SGEOLAN AND LOMAIR AND PASSING THE FIRBOLGS’ BURIAL MOUNDS CAME TO THE CAIRNHEAPED GRASSY HILL WHERE PASSIONATE MAIVE IS STONY`,
  `WE ARE APART IN THE GRASSY PLACES WHERE CARE CANNOT TROUBLE THE LEAST OF OUR DAYS OR THE SOFTNESS OF YOUTH BE GONE FROM OUR FACES OR LOVE’S FIRST TENDERNESS`,
  `MIGHTY BRAHMA’S EVER RUSTLING ROBE`,
  `YOU PHANTOMS WHITE AS SNOW WHOSE LIPS HAD LIFE’S MOST PROSPEROUS GLOW`,
  `US HE’S GOING THE`
]

const ts = 16

function setup() {
  createCanvas(400, 400);
  textAlign(RIGHT)
  textSize(ts)
}

function draw() {
  background(204, 40);
  translate(width / 2, height / 2);
  let a = atan2(mouseY - height / 2, mouseX - width / 2);
  rotate(a);
  // rect(-30, -5, 60, 10);
  // text('you spin me right round letter =>', 0, 0)

  texts.forEach(t => {
    text(t, -20, 0)
    rotate(radians(ts))
  })

}